- name: Remove old Node.js completely
  apt:
    name:
      - nodejs
      - libnode72
    state: absent
    purge: yes
  become: yes

- name: Remove unused packages
  apt:
    autoremove: yes
  become: yes

- name: Clean apt cache
  apt:
    autoclean: yes
  become: yes

- name: Install NodeSource repo (Node 18)
  shell: curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
  args:
    executable: /bin/bash
  become: yes

- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: yes
  become: yes

- name: Check Node version
  command: node -v
  register: node_version

- debug:
    var: node_version.stdout

- name: Install PM2
  npm:
    name: pm2
    global: yes
  become: yes

- name: Install app dependencies
  shell: npm install
  args:
    chdir: /opt/nodeapp

- name: Start Node app with PM2
  shell: |
    pm2 start app.js --name nodeapp || pm2 restart nodeapp
  args:
    chdir: /opt/nodeapp