[jenkins]
jenkins-server ansible_host=192.168.1.231 ansible_user=jenkins ansible_password=admin

[lb]
lbstack ansible_host=192.168.1.230 ansible_user=lbstack ansible_password=admin ansible_become_password=admin

[web]
node1 ansible_host=192.168.1.232 ansible_user=node1 ansible_password=admin
node2 ansible_host=192.168.1.233 ansible_user=node2 ansible_password=admin